grafana:
  enabled: false

alertmanager:
  enabled: false

defaultRules:
  create: false

prometheus:
  prometheusSpec:
    retention: 6h
    scrapeInterval: 15s
    evaluationInterval: 15s

    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: "1"
        memory: 1Gi

    nodeSelector:
      anfa.dev/role: infrastructure

    tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule

prometheusOperator:
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 256Mi

  nodeSelector:
    anfa.dev/role: infrastructure

  tolerations:
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
      effect: NoSchedule

kube-state-metrics:
  nodeSelector:
    anfa.dev/role: infrastructure

  tolerations:
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
      effect: NoSchedule

  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 192Mi

nodeExporter:
  enabled: false

prometheus-node-exporter:
  enabled: false

kubeControllerManager:
  enabled: false

kubeScheduler:
  enabled: false

kubeEtcd:
  enabled: false

coreDns:
  enabled: false

kubeProxy:
  enabled: false
