apiVersion: v1
kind: Service
metadata:
  name: predictive-autoscaler-safety
  namespace: default
spec:
  type: NodePort
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/name: predictive-autoscaler
  ports:
    - name: safety-http
      port: 8081
      targetPort: health
      nodePort: 30081
      protocol: TCP
