apiVersion: v1
kind: ServiceAccount
metadata:
  name: predictive-autoscaler
  namespace: default
  labels:
    app.kubernetes.io/name: predictive-autoscaler
    app.kubernetes.io/version: "1.0.0"
    anfa.dev/component: controller
automountServiceAccountToken: true
