apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: benchmark-app
  labels:
    app.kubernetes.io/name: benchmark-app
    anfa.dev/component: benchmark
    release: artifact-monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: benchmark-app
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      scrapeTimeout: 5s
